name: Run calculate_latency.py on Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-calculate-latency:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10  
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas  
          pip install tqdm

      - name: Run calculate_latency.py script
        run: |
          python calculate_latency.py  # This will execute your script
          
      - name: Commit and Push CSV files (if changes detected)
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # Check for changes
          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git pull
            git add Addenda/Latency/*.csv  
            git commit -m "Updated latency csvs on push"
            git push
          fi
